### ISSUE TITLE
我想改鸿蒙黑体， 但是不会用

### ISSUE THREAD

**Issue by abigmiu** [codehz/YaHei-Build#2]
我改了这两处， 但是打印出来是个空数组（见图三）

![image](https://user-images.githubusercontent.com/43983920/166229875-f939e8b4-07de-4ed6-878f-28e476db4918.png)
![image](https://user-images.githubusercontent.com/43983920/166229888-023a75c5-2de2-40ec-8786-c5c36f0d9382.png)
![image](https://user-images.githubusercontent.com/43983920/166230091-0340edda-ddbb-4565-9474-089b14ad2d66.png)

**Comment by codehz** [comment]
你用fontforge (gui)打开看看

**Comment by abigmiu** [comment]
> 你用fontforge (gui)打开看看

解决不了
